name = "aha-stack-example"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-11-28"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "aha-stack.casoon.dev", custom_domain = true }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
